sonar.projectKey=sapphire-sh_sapphire-utils
sonar.organization=sapphire-sh
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
