name: npm-audit-fix

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fix:
    uses: sapphire-sh/github-actions/.github/workflows/npm-audit-fix-template.yml@main
    permissions:
      contents: write
      issues: write
      pull-requests: write
