name: npm-publish

on:
  push:
    branches: [main]

jobs:
  publish:
    permissions:
      contents: write
      packages: write
      id-token: write
    uses: sapphire-sh/github-actions/.github/workflows/npm-publish-template.yml@main
    with:
      run_tests: true
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      MATTERMOST_CHANNEL_ID: ${{ secrets.MATTERMOST_CHANNEL_ID }}
      MATTERMOST_TOKEN: ${{ secrets.MATTERMOST_TOKEN }}
      MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
